### ISSUE TITLE
Show recording ID on view screen 

### ISSUE THREAD

**Issue by BruceMcC** [TheCacophonyProject/cacophony-web-old#109]
I've just been reviewing some recordings. And I'd find it really handy if the recording ID was displayed along with the device and date/time. That would let me note down a recording that I might want to refer back to later.

**Comment by mjs** [comment]
You can find the recording ID in the URL, but I agree it would be helpful to also have the ID on the page.

Note that it's often useful to keep the full URL in the URL bar if you want to refer back to a recording.

**Comment by arthurmcgregor** [comment]
How does this look?

![issue109](https://user-images.githubusercontent.com/24260476/43117726-5f984d5c-8f62-11e8-9e59-322fe6850bb5.png)

(I've also added the same to the vuex repo but won't come through until after my other PR because I forgot to make a new branch earlier!)

**Comment by mjs** [comment]
@arthurmcgregor LGTM
