### ISSUE TITLE
Inconsistent date formats on Search Video Recordings page

### ISSUE THREAD

**Issue by BruceMcC** [TheCacophonyProject/cacophony-web-old#110]
Date formats in dialog boxes are mm/dd/yy. Suggest change to dd/mm/yy as per dates below.

**Comment by arthurmcgregor** [comment]
I think this is a browser/localisation setting. On my computer it shows up dd/mm/yyyy. From a code point of view, all that is specified is `<input type="date">` and the browser handles the rest.

![issue110](https://user-images.githubusercontent.com/24260476/43117887-4601223c-8f63-11e8-90f3-4c5c88fa3839.png)
