### ISSUE TITLE
Some minor upgrades for tagging page

### ISSUE THREAD

**Issue by GrantRyan** [TheCacophonyProject/cacophony-web-old#23]
Good to have a delete button on page
Good to have the default the same as the previous video - eg human, possum, bird etc....tend to do heaps at once - it can beome a pain when you have to select animal, interaction and trap type repeating
Maybe have a comment field so can write anything want about particular videos
Button if video is particularly interesting?
Need a tag for insect and spider    (insect and spider currently tagged as other...)
Would be great to see tags listed in the "get recordings" page
Cool to have a summary page with the number of different tagged videos - then maybe a way to look at just the mice etc?
Maybe a "next untagged video" button

**Comment by mjs** [comment]
Most of these have been done. #34 has tags displayed on the "get recordings" page.

The only thing missing is a button if something is particularly interesting. I'll create a separate issue for that.
