### ISSUE TITLE
Tag delete button doesn't work

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-old#53]
The AJAX request to delete the tag is returned 422. This could be a problem with the request or a regression in the API server.

**Comment by arthurmcgregor** [comment]
Where is the delete tag button that is causing the problem?

**Comment by mjs** [comment]
On the "view recording" page. There's a trashcan next to each tag. Clicking it should delete the tag but the API request currently fails. 

I'm not sure if the problem is that the frontend isn't generating the correct API request or if there's a problem at the API server end.

**Comment by arthurmcgregor** [comment]
Ah - it's another firefox bug which is why I didn't spot it first time around! (because the delete tag button works for me on chrome) That suggests it's a front end issue, not an API issue. Probably the same issue as with the last button.... I'll look into it.

**Comment by mjs** [comment]
There's still an issue here. The tag delete button doesn't work for me (using Chromium)

**Comment by mjs** [comment]
The API request fails with a 400 status and `{"success":false,"messages":["Failed to delete tag."]}`

The request is a DELETE to `/api/v1/tags` with the following body:
```
tagId=5595
```

**Comment by arthurmcgregor** [comment]
I don't know what the problem is. It is working for me. I can delete tags when testing via Postman as well. It is calling the correct api with the correct body so it isn't the bug that was the problem earlier in the issue.... I don't have Chromium (and couldn't find a download link!) so can't reproduce this error either.

Sorry!

**Comment by mjs** [comment]
No worries. I'll take a look at some point.
