### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-web-old#76]
We haven't been all that great at making sure that all parts of the UI work well on phones and tablets. Some screens have seen some love in this area recently (e.g. login and register) but other parts almost certainly don't work that well.

**Comment by arthurmcgregor** [comment]
Would it be worth upgrading to Bootstrap 4 before doing much more here?

https://getbootstrap.com/docs/4.0/migration/#summary

**Comment by mjs** [comment]
@arthurmcgregor definitely open to doing that. any idea how hard that will be?

**Comment by arthurmcgregor** [comment]
So.... not exactly hard, just time consuming! Worth it though - much easier to style (either that or I'm just getting much better at bootstrap....)
