### ISSUE TITLE
Improve get recordings search (query) functionality

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-old#81]
- [x] Make the Device control a text field with autocomplete. The list in the dropdown is huge if you're an administrator with access to all the devices. Something like - but necessarily exactly - this: https://goodies.pixabay.com/javascript/auto-complete/demo.html
- [x] Change field called 'tags' to 'tag type' or 'tag class' (as opposed to animal tags)
- [x] Prettier and more compact layout of the form elements.
- [x] Allow the Device control to also select Device groups.
- [x] New control to allow selection of specific animal tags. The API supports this but we haven't exposed it in the UI yet.
- [x] Get rid of the two submit buttons. There should be just one button to query called 'search'
- [x] Get rid of the "Active query" bit or at least hide it by default.
- [x] Improve responsive layout for mobile
- [x] More obvious UX for date and duration selection. There should be no need for those Add buttons nor the "Conditions" section in the middle.

**Comment by arthurmcgregor** [comment]
Regarding the final point
> Change  field called 'tags' to 'tag type' or 'tag class' (as opposed to animal tags)

how about 'tag status'?

**Comment by mjs** [comment]
@arthurmcgregor "status" doesn't quite fit. It really is about the origin of the tag. "Tag source" or "Tag origin" could work?

**Comment by arthurmcgregor** [comment]
Hmmm I like "Tag source" but does it make sense for "untagged only" and "tagged only"?

**Comment by mjs** [comment]
@arthurmcgregor it doesn't really does it? hmmmm.... "Tag types" ?

**Comment by arthurmcgregor** [comment]
What is the format for an animal condition?
