### ISSUE TITLE
Offset doesn't reset when initiating a new query

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-old#95]
On the getRecordings page, if you are looking at a table with offset>0 and then run a different query, it will retain the offset and may potentially not display any results.

Perhaps best behaviour is for offset to reset to zero is the count is less than the offset, and then run the query again (so that some results will always be displayed)

**Comment by mjs** [comment]
I think resetting the offset to 0 every time the Search button is pushed makes sense.

I also wonder about the value of having the offset field be user visible at all. What do you think? The paging buttons are a much more useful way of delivering that functionality. 

Infinite scroll would be even more awesome but that's a lot more work :)

**Comment by arthurmcgregor** [comment]
Good plan. I'll hide the offset field and make it reset when search button pushed. 

I thought paging buttons at the bottom of the table might be useful too...

**Comment by mjs** [comment]
Happy for you to add some paging buttons at the bottom!
