### ISSUE TITLE
False-positive in query screen does not return any results (when it should)

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-web-old#96]
On getRecordings page, setting animal to false-positive does not return any results, even when running a query with no animal selected included recordings that have false positives

**Comment by arthurmcgregor** [comment]
@CameronRP How should I modify the API request to return false-positive results? I've tried a few things but without any luck.

**Comment by mjs** [comment]
This will require a change to the API server. False positives are represented in a different way in the API server's data model. They're not an animal type.

There will be a change required around here:
https://github.com/TheCacophonyProject/cacophony-api/blob/master/models/Recording.js#L119
